### ISSUE TITLE
Xack here.

### ISSUE THREAD

**Issue by zackp30** [yamikuronue/BusFactor#6]
Really really really sorry to make an issue here of all places (I couldn't PM you now! :frowning:)

Concerning https://meta.discourse.org/t/trouble-with-vagrant/32412

I have a feeling Docker isn't meant to be installed on it at all. The [docs](https://github.com/discourse/discourse/blob/master/docs/VAGRANT.md) mentioned in the Vagrantfile don't say anything about Docker, and it apparently comes with Discourse installed.

**Comment by yamikuronue** [comment]
Pasted to the thread: https://meta.discourse.org/t/trouble-with-vagrant/32412/11?u=yamikuronue

**Comment by zackp30** [comment]
One more thing, could you paste the errors into the thread?

Anyway, you can delete this issue now. I'll be patient and wait for the "ban" to expire, if you need me email zack@apertron.net

See ya!
